Generate metric_sender.yaml from template
openshift/openshift-tools pull request #1747
Opened 2016-12-08 11:50 UTC by zgalor

Generate the metric_sender.yaml file from template and place it in /etc/openshift_tools/metric_sender.yaml

2016-12-08 11:53 UTC, zgalor commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +    ssl_verify: "{{ osohm_hawk_verify_ssl }}"
@joelddiaz I wasn't sure whether and where I need to define those "osohm_hawk_web_url", etc.
I couldn't find a definition of the "zagg" ones.

2016-12-12 12:45 UTC, zgalor commented
@twiest @joelddiaz Could you please review? Lots of PRs depend on this one

2016-12-12 17:15 UTC, joelddiaz commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +    ssl_verify: "{{ osohm_hawk_verify_ssl }}"
@zgalor vars like osohm_zagg_* are passed into this oso_host_monitoring role, and the vars are defined in our private data hierarchy

2016-12-12 17:25 UTC, joelddiaz requested changes
For this PR, we should add a section into oso_host_monitoring/defaults/main.yml to house the off-by-default hawk variables. Basically just copying the defaults from docker/oso-host-monitoring/src/container_setup/monitoring-config.yml:

osohm_hawk_config:
  active: False
  url: https://localhost:8443
  user: admin
  pass: password
  ssl_verify: False
  verbose: False
  debug: False

Then in oso_host_monitoring/templates/monitoring-config.yml:

hawk: "{{ osohm_hawk_config }}"

Now when we stand up a hawkular server we'll be able to override this whenever we call out to the oso_host_monitoring role.

2016-12-12 17:32 UTC, joelddiaz commented
@zgalor probably should rebase on a recent prod b/c of changes in #1776

2016-12-13 08:26 UTC, zgalor commented
@joelddiaz I made the changes you requested. Please check

2016-12-13 14:54 UTC, joelddiaz approved these changes

2016-12-13 14:55 UTC, joelddiaz commented
@zgalor looks good. just need to resolve the merge conflict before we can merge this through

2016-12-13 15:18 UTC, zgalor commented
@joelddiaz Done

2016-12-13 15:56 UTC, merged