[WIP] local development with 'oc cluster up'
openshift/openshift-tools pull request #1826
Opened 2016-12-20 20:40 UTC by joelddiaz

2017-01-03 19:12 UTC, twiest requested changes

2017-01-03 19:12 UTC, twiest commented on docker/local_development/monitoring-secrets/opsmedic.yml
> +    -----END RSA PRIVATE KEY-----
Is this just to be used as an example?

Should this be a variable and set the default to this?

2017-01-03 19:12 UTC, twiest commented on docker/local_development/monitoring-secrets/zabbix-server-vars.yml
> +g_ses_smtp_server: email-smtp.us-east-1.amazonaws.com
None of these 3 values should be in openshift-tools.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/monitoring-secrets/zagg-server-vars.yml
> +    api_password: 'zabbix'
Why is this quoted?

2017-01-03 19:12 UTC, twiest commented on docker/local_development/monitoring-secrets/zagg-server-vars.yml
> +g_default_zagg_server_api_password: 'password'
Why is this quoted?

2017-01-03 19:12 UTC, twiest commented on docker/local_development/monitoring-secrets/zagg-server-vars.yml
> +g_default_zagg_server_password: supersecret
Can / should this be set as part of the template?

Might not be worth it, just wondering what your thoughts are on it.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +sudo iptables -F
Won't this basically remove my firewall rules?

This seems bad.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +${OC} deploy --latest oso-centos7-zabbix-web --follow
consider changing this to cent7 to be consistent.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +#!/bin/bash
Consider changing this to a `#!/bin/bash -e`

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +
We need to be pulling the latest images during this run, otherwise local dev will start using old images.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +sudo ${OC} cluster up
Make sure this script is re-runnable and that it either fails saying "instance already running" and points them cluster down script.

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +sudo docker exec oso-centos7-host-monitoring /usr/bin/ops-zagg-client --send-heartbeat
This already runs on container start up. Why is it needed here?

2017-01-03 19:12 UTC, twiest commented on docker/local_development/setup-local-dev-env.sh
> +#!/bin/bash
Consider renaming this script to "start-local-dev-env.sh" so that it's consistent with "stop-local-dev-env.sh"

2017-01-03 19:12 UTC, twiest commented on docker/local_development/stop-local-dev-env.sh
> +if [ "${OC}" -ne "0" ]; then
This should be comparing against `$?` right?

2017-01-03 19:12 UTC, twiest commented on docker/local_development/zabbix_monitoring_centos_local_dev.yaml
> +apiVersion: v1
Consider using the non-local development zabbix monitoring template using passed in vars.

2017-01-03 21:00 UTC, joelddiaz commented on docker/local_development/monitoring-secrets/opsmedic.yml
> +    -----END RSA PRIVATE KEY-----
Yes, just an example. In local development, there is no bastion host with an 'opsmedic' user defined.

2017-01-09 14:39 UTC, joelddiaz commented on docker/local_development/monitoring-secrets/zagg-server-vars.yml
> +g_default_zagg_server_password: supersecret
Just following how we do our secrets in production, but this could probably be done as a template (a secret template?).

2017-01-24 21:15 UTC, tiwillia commented
[test] again please!

2017-01-24 21:25 UTC, tiwillia commented
@joelddiaz the test failure appears to be legitimate, let me know if this is incorrect:
```
YAML validation failed on docker/local_development/zabbix_monitoring_cent7_local_dev.yaml: while scanning a simple key
  in "docker/local_development/zabbix_monitoring_cent7_local_dev.yaml", line 258, column 1
could not found expected ':'
  in "docker/local_development/zabbix_monitoring_cent7_local_dev.yaml", line 259, column 18
```

For some reason the build output was not included in the jenkins output, I'll have to look into that.

2017-02-01 15:47 UTC, joelddiaz commented
[test]

2017-02-01 20:58 UTC, joelddiaz commented
@twiest changes/feedback incorporated/addressed

2017-02-13 15:19 UTC, twiest requested changes
Looks amazing!

But we need to update 

https://github.com/openshift/openshift-tools/blob/prod/docs/local_development_monitoring.adoc

2017-02-14 15:15 UTC, twiest requested changes

2017-02-14 15:15 UTC, twiest commented on docs/local_development_monitoring.adoc
> +* Open a firewall port on port 53 so that OpenShift containers can do DNS resolution to other OpenShift containers. The change is ephemeral, so restarting firewalld should undo the change.
These are not seen as bullit points in the rendered doc here:
https://github.com/joelddiaz/openshift-tools/blob/3212168bde24602fd92d9e9f94a1a81872e74682/docs/local_development_monitoring.adoc#running-the-monitoring-containers-locally

2017-02-14 15:15 UTC, twiest commented on docs/local_development_monitoring.adoc
> +* Stop the local OpenShift environemnt with `oc cluster down`
same

2017-02-14 15:22 UTC, twiest approved these changes

2017-02-14 15:31 UTC, merged