Add OpenShift master audit config role.
openshift/openshift-tools pull request #1957
Opened 2017-01-23 15:21 UTC by dgoodwin

Configures the settings in auditConfig section of master-config.yaml.

Variables left unset indicates property should be removed if present, we
assume that if calling this role, you intend to manage that section of
config and have passed appropriate vars.

2017-01-30 19:47 UTC, mwoodson requested changes

2017-01-30 19:47 UTC, mwoodson commented on ansible/roles/openshift_master_audit_config/tasks/main.yml
> +
Can we combine these into a with_items passed into yedit?  Thoughts?

2017-01-31 13:45 UTC, dgoodwin commented
@mwoodson ok this is updated now, the empty string default is the only thing I can find that works correctly in terms of removing settings if you don't want them set anymore. Looking at upstream origin docs I don't think setting empty string has any value and is likely invalid.

2017-01-31 16:37 UTC, dgoodwin commented
@mwoodson ok this is updated now, the empty string default is the only thing I can find that works correctly in terms of removing settings if you don't want them set anymore. Looking at upstream origin docs I don't think setting empty string has any value and is likely invalid.

2017-01-31 20:15 UTC, mwoodson approved these changes

2017-01-31 20:20 UTC, merged