Add job that reports docker oc rpm versions daily
openshift/openshift-tools pull request #2081
Opened 2017-02-14 11:10 UTC by zgalor

2017-02-14 11:14 UTC, zgalor commented
@twiest @joelddiaz PTAL

2017-02-15 13:47 UTC, twiest requested changes

2017-02-15 13:47 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: ops-runner -f -s 120 -n csdov.rpm.versions /usr/bin/cron-send-docker-oc-versions
What does this do when run against zabbix?

I think we need zabbix items to catch these. Do you agree?

2017-02-15 14:00 UTC, zgalor commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: ops-runner -f -s 120 -n csdov.rpm.versions /usr/bin/cron-send-docker-oc-versions
What would happen on zabbix if the item isn't defined? Will it just be ignored?

I'm not sure we need it on zabbix. It's not a metric. We are simply using hawkular as a medium to transfer data that we can check against expected values in manageIQ policies.

2017-02-17 18:21 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: ops-runner -f -s 120 -n csdov.rpm.versions /usr/bin/cron-send-docker-oc-versions
Yeah, we have this for some things (like kernel version).

Here's an example:
https://github.com/openshift/openshift-tools/blob/prod/ansible/roles/os_zabbix/vars/template_os_linux.yml#L71-L74


Check some of the PCP items for more details.

2017-02-20 16:16 UTC, zgalor commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: ops-runner -f -s 120 -n csdov.rpm.versions /usr/bin/cron-send-docker-oc-versions
I can add that task in the zabbix ansible template, but I can't test it so I think it's best if someone from your end adds it, if you think you need that info on zabbix.

2017-02-20 19:41 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: ops-runner -f -s 120 -n csdov.rpm.versions /usr/bin/cron-send-docker-oc-versions
@zgalor You can't use the zaio to test this out?

My concern is that we're going to start having some checks in one and not the other. I think we need to keep these in sync.

2017-02-21 12:24 UTC, zgalor commented
@twiest I added zabbix keys for new metrics

2017-02-21 13:35 UTC, twiest requested changes

2017-02-21 13:35 UTC, twiest commented on ansible/roles/os_zabbix/vars/template_openshift_master.yml
> +  - key: atomic-openshift-master.version
Hmm, this naming scheme of the key doesn't really fit in with the rest of the master keys.

I didn't notice it in the other PR (sorry).

What are your thoughts on changing the key to be something like `openshift.master.version.atomic-openshift` ?

And the one above would be something like `openshift.master.version.origin-master`.

Obviously we'd want to change the node keys as well. The `docker.version` is prefect as is, though.

The reason that keeping the scheme the same is that we display metrics in zabbix using the "latest data" and its search is quite limited.

So if this is a different pattern, it won't show up if we search for "openshift.master" metrics.

2017-02-21 13:53 UTC, zgalor commented on ansible/roles/os_zabbix/vars/template_openshift_master.yml
> +  - key: atomic-openshift-master.version
I am sending rpm versions. So the pattern is the `<name of the rpm>.version`.
It also needs to be verified against expected values you push to manageIQ using ansible playbooks.
If hawkular that allows searching by tags, and manageIQ are the future, is it really worth complicating the keys to match a pattern in zabbix, we are planning to replace anyway?

2017-02-23 08:11 UTC, zgalor commented
@twiest renamed according to what we discussed and added descriptor_name tag.
Please review

2017-02-27 14:58 UTC, twiest commented
@zgalor please fix the branch conflicts and I'll re-review.

2017-03-01 08:05 UTC, zgalor commented
@twiest rebased

2017-03-01 14:42 UTC, twiest approved these changes

2017-03-01 14:43 UTC, merged