changing zagg target to service IP from skydns provided local dns name
openshift/openshift-tools pull request #2149
Opened 2017-02-24 18:52 UTC by ivanhorvath

2017-02-24 18:57 UTC, ivanhorvath commented
Was pondering if we should use another check and make sure whatever is given is an ip address, but the ansible jinja filter ipaddr requires more packages to be installed, so I left it out for now. @twiest you wanted the container to not even start up if we can't get a connection? So we should check if it can connect to the zagg on host-monitoring container startup?

2017-02-27 14:54 UTC, twiest requested changes

2017-02-27 14:54 UTC, twiest commented on docker/oso-host-monitoring/centos7/root/config.yml
> +    register: svcipout
will fail on tower

2017-02-27 17:00 UTC, twiest approved these changes

2017-02-27 17:04 UTC, merged