Add generic pod template deployer role
openshift/openshift-tools pull request #2221
Opened 2017-03-10 17:40 UTC by themurph

2017-03-13 18:35 UTC, themurph commented
/cc @mwoodson @jupierce - Basic tests passed after some cleanup. Ready for testing.

2017-03-13 18:54 UTC, mwoodson requested changes

2017-03-13 18:54 UTC, mwoodson commented on ansible/roles/openshift_template_deployer/README.md
> +openshift_volume_provisioner
This file needs to be updated with the variables that are now being used, and the purpose of it.

2017-03-13 18:54 UTC, mwoodson commented on ansible/roles/openshift_template_deployer/defaults/main.yml
> +#- name: SYNC_PERIOD
we should clean these up. I don't think they are needed.

2017-03-13 18:54 UTC, mwoodson commented on ansible/roles/openshift_template_deployer/handlers/main.yml
> +  - "{{ osvp_master_nodes }}"
this variable is wrong.  it needs the new name on it.

2017-03-13 18:54 UTC, mwoodson commented on ansible/roles/openshift_template_deployer/meta/main.yml
> +- role: tools_roles/lib_openshift_3.2
we might want to switch this over to use the openshift-ansible lib_openshift and lib_yaml_editor.

2017-03-13 18:59 UTC, themurph commented on ansible/roles/openshift_template_deployer/handlers/main.yml
> +  - "{{ osvp_master_nodes }}"
We all waivered on just removing the handler, but I'll update the variable just in case we decide to keep this file.

2017-03-14 02:12 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +    msg:  "Please ensure that 'osvp_<variables>' are set!"
Should be "Please ensure that **ostd**_variables are set!"

2017-03-14 02:15 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +    node_selector: "{{ ostd_node_selector|default(omit)}}"
Missing space before }} on several of these. @mwoodson suggested this as a style guideline.

2017-03-14 02:16 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +    params: "{{ ostd_template_params|default(omit)}}"
Space before }}

2017-03-14 02:29 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +  when: ostd_template_edits
I think all of these  `when: X` statements need to be  `when: X is defined`

2017-03-14 02:36 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +  with_items: "{{ ostd_template_edits }}"
In addition, if the task protected by the `when:` uses the variable, I needed to do something like "{{ ostd_template_edits | default(omit) }}" or else I would get an error that the variable was undefined.

2017-03-14 02:42 UTC, jupierce commented on ansible/roles/openshift_template_deployer/defaults/main.yml
> +ostd_project_display_name: "{{ ostd_project_name }}"
I think this should be `{{ ostd_project }}`  instead.

2017-03-14 02:50 UTC, jupierce commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +- name: create project
Received a pretty odd error on this task: 
```
TASK [tools_roles/openshift_template_deployer : create project] ****************
fatal: [cicd-master-14aa4]: FAILED! => {"changed": false, "failed": true, "msg": {"cmd": "/usr/bin/oc -n jupierce-test replace -f /tmp/jupierce-test", "results": {}, "returncode": 1, "stderr": "Error from server (BadRequest): error when replacing \"/tmp/jupierce-test\": Namespace in version \"v1\" cannot be handled as a Namespace: [pos 93]: json: expect char '\"' but got char 'n'\n", "stdout": ""}}
```
The project seemed to have been created the first time I ran the task, but this error occurs now.

2017-03-14 16:53 UTC, themurph commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +  with_items: "{{ ostd_template_edits }}"
Fixed

2017-03-14 16:54 UTC, themurph commented on ansible/roles/openshift_template_deployer/tasks/main.yml
> +  when: ostd_template_edits
fixed

2017-03-14 17:48 UTC, themurph commented
@mwoodson and @jupierce - All updates we discussed this morning are in and all tests passed

2017-03-14 20:33 UTC, mwoodson approved these changes

2017-03-14 21:06 UTC, jupierce commented
@themurph There was a small change that needed to be made in your absence (lib_yaml_editor => lib_utils). #2240 has been created to introduce that change.

2017-03-14 21:06 UTC, closed without merging