add checks for docker rss and vms[WIP]
openshift/openshift-tools pull request #2279
Opened 2017-03-23 07:18 UTC by BlueShells

this script will collect the docker memory usage rss and vms ,but not on the master (if we need the usage of docker master ,I will change the function ) and the application is "Docker Daemon"

2017-03-28 06:48 UTC, drewandersonnz requested changes
should this be: memoryusage with an 's'?

2017-03-28 06:48 UTC, drewandersonnz commented on scripts/monitoring/cron-send-docker-metrics.py
> +            keys['docker.memoryuage.rss'] = int(docker_memoryusage['rss'])
should this be: memoryusage with an 's'?

2017-03-28 06:48 UTC, drewandersonnz commented on scripts/monitoring/cron-send-docker-metrics.py
> +            keys['docker.memoryuage.vms'] = int(docker_memoryusage['vms'])
should this be: memoryusage with an 's'?

2017-03-28 06:48 UTC, drewandersonnz commented on ansible/roles/os_zabbix/vars/template_docker.yml
> +  - key: docker.memoryuage.vms
should this be: memoryusage with an 's'?

2017-03-28 06:48 UTC, drewandersonnz commented on ansible/roles/os_zabbix/vars/template_docker.yml
> +  - key: docker.memoryuage.rss
should this be: memoryusage with an 's'?

2017-03-28 13:17 UTC, twiest commented
[test]

2017-03-28 13:39 UTC, twiest commented
[test]

2017-03-28 13:43 UTC, twiest commented
[test]

2017-03-28 13:48 UTC, twiest commented
@BlueShells The bot is working now. The failure above is a valid failure (you need to fix some stuff).

See the output of the build bot for more details.

2017-03-29 00:50 UTC, drewandersonnz approved these changes
+1

2017-03-29 00:53 UTC, merged