fix the bug that in the new version of openshift used clusterresource…
openshift/openshift-tools pull request #2280
Opened 2017-03-23 08:08 UTC by BlueShells

fix the bug that in the new version of openshift used clusterresourcequota

2017-03-24 01:10 UTC, drewandersonnz requested changes
@BlueShells just a few "code flair" things to tidy, and can you please confirm the pv_used if it needs conversion or not?

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
>          pv_used = get_pv_usage()
@BlueShells, does this pv_used need to be converted?

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
> +
please remove the extra whitespace (3 empy lines) above here, leave one empty line between this and the next function

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
> +    """covert to ki"""
"""convert to bytes"""

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
> +    """cover to kib"""
convert

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
> +    """cover to mb"""
convert

2017-03-24 01:10 UTC, drewandersonnz commented on scripts/monitoring/cron-send-usage-pv.py
> +    """covert to gb"""
convert

2017-03-24 04:40 UTC, BlueShells commented on scripts/monitoring/cron-send-usage-pv.py
>          pv_used = get_pv_usage()
this don't needed , unless openshift changed in next version

2017-03-27 05:56 UTC, drewandersonnz approved these changes
+1

2017-03-29 02:25 UTC, merged