Allow parameters to be passed to cicd-control.sh.
openshift/openshift-tools pull request #2281
Opened 2017-03-23 10:49 UTC by bbguimaraes

@jupierce (@joelsmith?): PTAL.

The diff is a little convoluted because of all the whitespace changes.
`git diff --ignore-all-space` gives a better view of what's being changed.

2017-03-23 15:36 UTC, joelsmith requested changes
The verification stuff looks good. We just have the issue of the `cicd-control` script not being installed on the host in an approved way.

2017-03-23 15:36 UTC, joelsmith commented on scripts/cicd/verify-cicd-operation.py
> +        runner("/home/opsmedic/aos-cd/git/aos-cd-jobs/bin/cicd-control.sh", keyname, *cmd)
We still need cicd-control.sh to be installed by RPM, not just some script from a repo. Does that script really take keyname as an argument?

2017-03-23 18:42 UTC, jupierce commented on scripts/cicd/verify-cicd-operation.py
> +        runner("/home/opsmedic/aos-cd/git/aos-cd-jobs/bin/cicd-control.sh", keyname, *cmd)
@joelsmith The RPM work is underway (e.g. #2269 and others ).

keyname is actually a cluster name (e.g. 'dev-preview-int').

2017-03-23 18:54 UTC, jupierce commented
Thanks @bbguimaraes! 
@themurph @mwoodson ptal . 
@themurph once merged, this will need to drive a new RPM build.

2019-10-14 15:23 UTC, stevekuznetsov commented
/close

2019-10-14 15:23 UTC, closed without merging