cron changes based on arch meeting discussions
openshift/openshift-tools pull request #2571
Opened 2017-05-31 15:10 UTC by ivanhorvath

2017-05-31 16:44 UTC, ivanhorvath commented
[test]

2017-05-31 19:06 UTC, twiest requested changes
Looking good other than my comments.

2017-05-31 19:06 UTC, twiest commented on ansible/roles/os_zabbix/vars/template_os_linux.yml
> +    expression: "{Template OS Linux:kernel.uname.sysname.max(#3)}<1"
I believe uname.sysname is a string, therefore a numeric operation (`max`) won't work on it.

Consider using `nodata` instead.

Also, make sure you test this to make sure it's having the desired effect.

2017-05-31 19:06 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  minute: "*/2"
This should be in sync with the normal heartbeat, which is set to every 3 minutes.

Sorry, I probably screwed up and said 2 here.

2017-05-31 19:06 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: "ops-runner -f -s 15 -n cseeviss.ebs.stuck.state cron-send-ec2-ebs-volumes-in-stuck-state --region {{ osohm_region }} --stuck-after 120 --aws-creds-profile snapshotter --verbose"- name: "Check
This change looks wrong. Was this intentional?

2017-05-31 19:08 UTC, ivanhorvath commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> +  job: "ops-runner -f -s 15 -n cseeviss.ebs.stuck.state cron-send-ec2-ebs-volumes-in-stuck-state --region {{ osohm_region }} --stuck-after 120 --aws-creds-profile snapshotter --verbose"- name: "Check
Ahh yes, this is the result of tower not responding while clicking around the screen, probably selected and copied stuff. Good catch.

2017-05-31 19:24 UTC, ivanhorvath commented on ansible/roles/os_zabbix/vars/template_os_linux.yml
> +    expression: "{Template OS Linux:kernel.uname.sysname.max(#3)}<1"
Good call, tested it in local dev, it works with nodata.

2017-06-01 13:10 UTC, twiest requested changes
This is very close to ready.

2017-06-01 13:10 UTC, twiest commented on ansible/roles/os_zabbix/vars/template_os_linux.yml
> +    priority: average
Ok, I spent a lot of time last night thinking about this.

For posterity, here are the tradeoffs:
Good:
* this is reusing an item we're already sending

Bad:
* nodata is going to cause this trigger to fire for all cases where the heartbeat trigger will fire (doubling them up)
* nodata is more expensive than max


Given the above tradeoffs, I think I prefer keeping it the way it was, so I suggest getting rid of these changes.

2017-06-01 13:10 UTC, twiest commented on ansible/roles/oso_host_monitoring/templates/monitoring-config.yml.j2
> -  job: ops-runner -f -s 60 -n cspp.pcp.ping /usr/bin/cron-send-pcp-ping
Keep this section (i.e. undo this change), but have it to run every 10 minutes.

2017-06-01 14:04 UTC, ivanhorvath commented on ansible/roles/os_zabbix/vars/template_os_linux.yml
> +    priority: average
Changed this back.

2017-06-01 14:47 UTC, twiest approved these changes
Looks amazing!

2017-06-01 14:48 UTC, merged