add openshift_disk_provision role
openshift/openshift-tools pull request #2741
Opened 2017-07-19 20:59 UTC by blentz

2017-07-19 21:24 UTC, kwoodson requested changes
Few clean up issues here.

2017-07-19 21:24 UTC, kwoodson commented on ansible/roles/openshift_disk_provision/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
Prefer a new line character here.

2017-07-19 21:24 UTC, kwoodson commented on ansible/roles/openshift_disk_provision/meta/main.yml
> +  # If the issue tracker for your role is not on github, uncomment the
Remove all generated junk.

2017-07-19 21:28 UTC, blentz commented on ansible/roles/openshift_disk_provision/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
fwiw... this is just the auto-generated file that "ansible-galaxy --init" creates.

Are you meaning a newline between lines 28 and 29?

2017-07-19 21:28 UTC, blentz commented on ansible/roles/openshift_disk_provision/meta/main.yml
> +  # If the issue tracker for your role is not on github, uncomment the
Sure. Easy enough.

2017-07-19 21:30 UTC, kwoodson commented on ansible/roles/openshift_disk_provision/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
In the `Files Changed` view it shows a red circle with a new line character missing.  I'd prefer we add one so that it is not missing.

2017-07-19 21:32 UTC, blentz commented on ansible/roles/openshift_disk_provision/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
Ah ha. Gotcha. Sure thing.

2017-07-21 14:00 UTC, kwoodson approved these changes

2017-07-21 14:03 UTC, kwoodson commented
@blentz, it looks like this failed because of the back ported code doesn't pass the linter.  I see 2 options here:

-  place a disable in the file for pylint on backported code
-  ignore the backported code in this portion of the PR

2017-07-24 18:52 UTC, merged