Adding include_role to best practices.
openshift/openshift-tools pull request #2762
Opened 2017-08-02 02:29 UTC by kwoodson

2017-08-02 17:14 UTC, twiest requested changes
Looks good, one minor comment.

2017-08-02 17:14 UTC, twiest commented on docs/best_practices_guide.adoc
> +| Playbooks SHOULD not use pre_tasks, post_tasks, and roles: sections.  Should use tasks: and include_role:.
Consider capitalizing the "not" in "SHOULD not" as without the caps, it isn't being emphasized and while skim reading, I thought that said it "SHOULD" use pre_tasks & co.

2017-08-08 15:07 UTC, kwoodson commented
@twiest @joelddiaz Please approve.

2017-08-21 19:54 UTC, twiest approved these changes

2017-08-21 20:07 UTC, merged