Adding scale group monitoring to the monitoring role.
openshift/openshift-tools pull request #3292
Opened 2018-02-05 20:21 UTC by kwoodson

2018-02-05 20:24 UTC, joelddiaz approved these changes

2018-02-05 20:25 UTC, mwoodson approved these changes

2018-02-05 21:32 UTC, joelddiaz requested changes

2018-02-05 21:32 UTC, joelddiaz commented on ansible/roles/oso_host_monitoring/tasks/scale_group.yml
> +        #kubernetes.io/hostname: ip-172-31-49-149.ec2.internal
extra stuff

2018-02-05 21:32 UTC, joelddiaz commented on ansible/roles/oso_host_monitoring/tasks/scale_group.yml
> +              dest: /host/root/.ssh/authorized_keys
add mode

2018-02-05 21:32 UTC, joelddiaz commented on ansible/roles/oso_host_monitoring/tasks/scale_group.yml
> +        #
extra line

2018-02-06 02:36 UTC, kwoodson commented on ansible/roles/oso_host_monitoring/tasks/scale_group.yml
> +              dest: /host/root/.ssh/authorized_keys
Added.  Its below

2018-02-06 02:48 UTC, merged