Fix host monitoring
openshift/openshift-tools pull request #3490
Opened 2018-04-20 22:12 UTC by portante

When a server is nearing overload, the cron jobs might take a long time
to start up just to be able to check the flock file given the overhead
of python.  If they can't start up quick enough, then they'll just keep
piling up as the cron deamon does not wait for the previous one to
finish.

By using the external flock command, and using /host/run/lock/ for the
location of the lock file, we avoid the python overhead of startup and
place the lock file in local memory.

Note that /host/run is the host's /run tmpfs mounted into the container.
f034be4

2018-04-22 00:15 UTC, dbaker-arch approved these changes
Usually we'd approve changes before they went to stg.  Since this is the merge to prod I'll +1 proviso it was tested there.

2018-04-23 11:08 UTC, joelddiaz commented
what happens when/if the host-monitoring container is terminated ungracefully? will some cron jobs refuse to start now that there are previous lock files permanently on the host filesystem?

also, aren't we reserving a minimum amount of cpu resources for openshift/host workloads through kubeletArguments.system-reserved?

2018-04-23 12:49 UTC, portante commented
> what happens when/if the host-monitoring container is terminated ungracefully? will some cron jobs refuse to start now that there are previous lock files permanently on the host filesystem?

Yes, good catch.  We can detect that situation in the container start.sh I believe.  I'll propose something.

> also, aren't we reserving a minimum amount of cpu resources for openshift/host workloads through kubeletArguments.system-reserved?

We are, but we've blown way past that due to other factors.

I don't believe in monitoring and logging collectors running as a docker container or under kubernetes, because they are monitoring the very subsystems in which they are running.  When the environment fails, monitoring fails.

Running this as a simple systemd service with the systemd service cron mechanism on the host would be the safest way to make sure monitoring does not affect the environment.

2018-04-27 18:19 UTC, twiest requested changes
The noc team, @portante  and I discussed this today and the conclusion is that this won't fix our overall problem and so we're going to punt on evaluating this for now.

I believe what we want is for ops-runner to continue to do the flock, but change where the flock is kept to a ramdisk location.

I would prefer the ramdisk be in the container, if possible. If not, then let's discuss what the next best would be.

2018-06-12 01:33 UTC, portante commented
@twiest, performing a flock on ramdisk in a container seems okay.

Closing this since its not considered a concern right now.

2018-06-12 01:33 UTC, closed without merging